### PR TITLE
bin - fix `launch` on windows

### LINKED ISSUE #1075: error[BCLE10]: Arma 3 Pointer `C` not found
```
error[BCLE10]: Arma 3 Pointer `C` not found
 = note: Tried loading mod `\Users\USERNAME\Documents\GitHub\advanced_slingloading_redux\.hemttout/dev`
```

Since 1.17.0, when trying to `hemtt launch` i am greeted with this error message.

Commit with error
https://github.com/OverlordZorn/advanced_slingloading_redux/commit/a0b0f33aa3efe9c8aa25005ea17e1f52c6708b03

### PR DESCRIPTION
**Pull request by PabstMirror**
fix #1075

### CODE REVIEW

File: bin/src/commands/launch/launcher.rs [hunk 1]
```diff
@@ -196,6 +196,10 @@ impl<'a> Launcher<'a> {
 
                 // Check if the mod starts with a pointer
                 if let Some((pointer, mod_path)) = load_mod.split_once(':') {
+                    if pointer.len() == 1 {
+                        // Skip drive letters
+                        continue;
```
Comment (PabstMirror) [inline bin/src/commands/launch/launcher.rs:201]: continue isn't right here
