### PR TITLE
preprocessor: fix duplicate pw3_padded_arg warnings

### LINKED ISSUE #642: `[PW3]: padding a macro argument` shown twice
```
warning[PW3]: padding a macro argument
   ┌─ addons/shootingrange/functions/fnc_create.sqf:89:99
   │
89 │     ERROR_1("Invalid triggers in Trigger Markers! Make sure all triggers are correctly set! (%1)", _name);
   │                                                                                                   ^ padding a macro argument
   │
   = note: padding a macro argument is likely unintended
   = note: occured in: `ERROR_1`


warning[PW3]: padding a macro argument
   ┌─ addons/shootingrange/functions/fnc_create.sqf:89:99
   │
89 │     ERROR_1("Invalid triggers in Trigger Markers! Make sure all triggers are correctly set! (%1)", _name);
   │                                                                                                   ^ padding a macro argument
   │
   = note: padding a macro argument is likely unintended
   = note: occured in: `FORMAT_1`
```

### PR DESCRIPTION
**Pull request by Eathox**
Fixes #642 

Honestly not sure if there's a cleaner more clever solution but this one works just fine. Please let me know if this is not adequate and or if there's anything you'd like to see changed.

### CODE REVIEW

File: libs/preprocessor/tests/warnings/pw3_padded_arg_inner/source.hpp [hunk 1]
```diff
@@ -0,0 +1,6 @@
+#define HELLO(var1, var2) INNER(Hello, var1##var2)
+#define GREET(var1, var2) INNER(Greetings, var1##var2)
```
Comment (BrettMayson) [inline libs/preprocessor/tests/warnings/pw3_padded_arg_inner/source.hpp:2]:
```suggestion
#define GREET(var1, var2) HELLO(Greetings, var1##var2)
```
Is that what was intended here? Otherwise I don't understand the difference

**Review by BrettMayson — APPROVED** [review]
